### ISSUE TITLE
JavaScript Track Courses to be completed

### ISSUE THREAD

**Issue by mrfr0st** [mrfr0st/Treehouse#1]
## TODO

_Courses left to complete the Treehouse JavaScript Track_
- [x] Finish Javascript Arrays and Objects
- [ ] JQuery Basics
- [ ] Using JQuery Plugins
- [ ] Interactive Web Pages with JavaScript
- [ ] AJAX Basics
- [ ] OOP JavaScript
- [ ] Node.js Basics
- [ ] Build a Simple Dynamic Site with Node.js
- [ ] npm Basics
- [ ] Express Basics
- [ ] Gulp Basics
- [ ] Angular Basics
- [ ] Mongo Basics
