### ISSUE TITLE
GitHub course to be completed

### ISSUE THREAD

**Issue by mrfr0st** [mrfr0st/Treehouse#2]
## TODO

_Finish GitHub course_
- [x] Hello, GitHub!
- [x] Working by yourself
- [x] Working on Team
- [x] Create a Web Presence on GitHub
- [x] Get Involved in Open Source

**Comment by mrfr0st** [comment]
Complete GitHub Basics course
