### ISSUE TITLE
Web Design

### ISSUE THREAD

**Issue by mrfr0st** [mrfr0st/Treehouse#4]
## TODO
- [ ] How to make a website
- [ ] CSS basics
- [ ] Css selectors
- [ ] HTML forms
- [ ] HTML tables
- [ ] CSS layouts basics
- [ ] Responsive layouts
- [ ] CSS flexbox layout
- [ ] Design foundations
- [ ] Photoshop foundations
- [ ] Adobe Illustrator for web design
- [ ] SVG Basics
- [ ] Animating SVG with CSS
